-- MySQL Script generated by MySQL Workbench
-- Thu Aug 20 13:07:35 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Conectados
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Conectados
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Conectados` DEFAULT CHARACTER SET utf8 ;
USE `Conectados` ;

-- -----------------------------------------------------
-- Table `Conectados`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Conectados`.`Users` (
  `uid` VARCHAR(36) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(50) NOT NULL,
  `isActive` TINYINT NOT NULL,
  `isRoot` TINYINT NOT NULL,
  `createAt` TIMESTAMP NOT NULL,
  PRIMARY KEY (`uid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Conectados`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Conectados`.`address` (
  `uid` VARCHAR(36) NOT NULL,
  `uidUser` VARCHAR(36) NOT NULL,
  `street` VARCHAR(100) NOT NULL,
  `number` VARCHAR(20) NOT NULL,
  `district` VARCHAR(50) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `state` VARCHAR(45) NOT NULL,
  `complement` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`uid`),
  INDEX `fk_address_Users_idx` (`uidUser` ASC) VISIBLE,
  CONSTRAINT `fk_address_Users`
    FOREIGN KEY (`uidUser`)
    REFERENCES `Conectados`.`Users` (`uid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Conectados`.`beneficiary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Conectados`.`beneficiary` (
  `uid` VARCHAR(36) NOT NULL,
  `uidUser` VARCHAR(36) NOT NULL,
  `singleCard` VARCHAR(45) NULL,
  `income` VARCHAR(45) NULL,
  PRIMARY KEY (`uid`),
  INDEX `fk_beneficiary_Users1_idx` (`uidUser` ASC) VISIBLE,
  CONSTRAINT `fk_beneficiary_Users1`
    FOREIGN KEY (`uidUser`)
    REFERENCES `Conectados`.`Users` (`uid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Conectados`.`legalPerson`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Conectados`.`legalPerson` (
  `uid` VARCHAR(36) NOT NULL,
  `uidUser` VARCHAR(36) NOT NULL,
  `socialReason` VARCHAR(100) NOT NULL,
  `fantasyName` VARCHAR(100) NOT NULL,
  `cnpj` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`uid`),
  INDEX `fk_legalPerson_Users1_idx` (`uidUser` ASC) VISIBLE,
  CONSTRAINT `fk_legalPerson_Users1`
    FOREIGN KEY (`uidUser`)
    REFERENCES `Conectados`.`Users` (`uid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Conectados`.`physicalPerson`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Conectados`.`physicalPerson` (
  `uid` VARCHAR(36) NOT NULL,
  `uidUser` VARCHAR(36) NOT NULL,
  `firstName` VARCHAR(100) NOT NULL,
  `lastName` VARCHAR(100) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`uid`),
  INDEX `fk_physicalPerson_Users1_idx` (`uidUser` ASC) VISIBLE,
  CONSTRAINT `fk_physicalPerson_Users1`
    FOREIGN KEY (`uidUser`)
    REFERENCES `Conectados`.`Users` (`uid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Conectados`.`voluntary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Conectados`.`voluntary` (
  `uid` VARCHAR(36) NOT NULL,
  `uidUser` VARCHAR(36) NOT NULL,
  `help` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`uid`),
  INDEX `fk_voluntary_Users1_idx` (`uidUser` ASC) VISIBLE,
  CONSTRAINT `fk_voluntary_Users1`
    FOREIGN KEY (`uidUser`)
    REFERENCES `Conectados`.`Users` (`uid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
